//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.5446
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQE {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure rigenerare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameData() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CQE.GameData", typeof(GameData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] Arms {
            get {
                object obj = ResourceManager.GetObject("Arms", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] axes {
            get {
                object obj = ResourceManager.GetObject("axes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] bows {
            get {
                object obj = ResourceManager.GetObject("bows", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Decorations {
            get {
                object obj = ResourceManager.GetObject("Decorations", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dualswords {
            get {
                object obj = ResourceManager.GetObject("dualswords", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] greatswords {
            get {
                object obj = ResourceManager.GetObject("greatswords", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gunlances {
            get {
                object obj = ResourceManager.GetObject("gunlances", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] hammers {
            get {
                object obj = ResourceManager.GetObject("hammers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] heavygun {
            get {
                object obj = ResourceManager.GetObject("heavygun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Helms {
            get {
                object obj = ResourceManager.GetObject("Helms", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] horns {
            get {
                object obj = ResourceManager.GetObject("horns", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] lances {
            get {
                object obj = ResourceManager.GetObject("lances", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Legs {
            get {
                object obj = ResourceManager.GetObject("Legs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] lightgun {
            get {
                object obj = ResourceManager.GetObject("lightgun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] longswords {
            get {
                object obj = ResourceManager.GetObject("longswords", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Plates {
            get {
                object obj = ResourceManager.GetObject("Plates", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] shieldandswords {
            get {
                object obj = ResourceManager.GetObject("shieldandswords", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SkillList {
            get {
                object obj = ResourceManager.GetObject("SkillList", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Waists {
            get {
                object obj = ResourceManager.GetObject("Waists", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
